# Generated by Django 2.1.3 on 2018-11-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20181127_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plant.PlantType'),
            preserve_default=False,
        ),
    ]
